#!/bin/bash

echo "Minutes of inhabilititation:"
read minutes
count=$minutes
(while :; 
do 
	echo "$count left"
	qdbus org.kde.screensaver /ScreenSaver SimulateUserActivity; 
	sleep 50s; 
	count=$[ $count - 1 ]
done)& 
sleep $[$minutes*60]; 
kill $!
