#!/bin/bash

if [ -f ~/.upgrade.local ];
then
	~/.upgrade.local
fi

if [ $EUID -ne 0 ]
then
    sudo aptitude update 2>/dev/null
    sudo aptitude -y safe-upgrade
    sudo aptitude clean
else
	aptitude update 
    aptitude -y safe-upgrade
    aptitude clean
fi
