#!/bin/bash

read -p "Name:" name
read -p "Email:" email
read -p "Core editor[vim]:" editor
if [[ $editor == "" ]]
then
	editor="vim"
fi

read -p "Diff tool[vimdiff]" difftool
if [[ $difftool == "" ]]
then
	difftool="vimdiff"
fi

read -p "Merge tool[vimdiff]:" mergetool
if [[ $mergetool == "" ]]
then
	mergetool="vimdiff"
fi

read -p "Push default[SIMPLE/matching]:" pushdef
if [[ $pushdef == "" ]]
then
	pushdef="simple"
fi

read -p "Activate credential helper? [Y/n]:" credential
if [[ $credential == "" ]]
then
	credential="y"
fi

read -p "Credential timeout? [3600]:" timeout
if [[ $timeout == "" ]]
then
	timeout="3600"
fi

git config --global user.name "$name"
git config --global user.email "$email"
git config --global core.editor "$editor"
git config --global diff.tool "$difftool"
git config --global merge.tool "$mergetool"
git config --global push.default "$pushdef"
if [[ $credential =~ ^[Yy]$ ]]
then
	git config --global credential.helper cache --timeout=$timeout
else
	git config --global --unset credential.helper 
fi

git config --global alias.co checkout
git config --global alias.ci commit
git config --global alias.st status
git config --global alias.undo reset --hard
git config --global alias.br branch
git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset - %C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue) <%an>%Creset' --abbrev-commit"
git config --global alias.up "submodule foreach git pull"
