#!/bin/bash

#@TODO: Uninstall

utilpath=$(dirname $(readlink -f $0))
cd $utilpath

cd ..

utilpath=$(pwd)

git pull https://github.com/mansonjesus/cliutils.git master 1>&1 | grep "Already up-to-date."

if [[ ! $? -eq 0 ]]; then
    while read origin dest; do

        ln -s $(pwd)/$origin $dest 2>/dev/null

        if [ $? -ne 0 ]
        then 
            sudo ln -s $(pwd)/$origin $dest 2>/dev/null
            sudo chmod +x $origin
        else
            chmod +x $origin
        fi
    done < data/links.db
fi

if [[ -z $CLIUTILS ]]; then
	echo -e "\n Please insent next code in youn shell rc file:\n\n\tsource \"$utilpath/lib/func\"\n\n"; 
	$utilpath/lib/func
fi

