#!/usr/bin/python

import os
import subprocess

# @TODO: Execute update script instead git pull
repos = '~/.local/repos.txt'

if not os.path.exists(os.path.expanduser(repos)):
    os.system("vi "+repos)

f = open(os.path.expanduser(repos), 'r+')

for line in f:
	print line
	pr=subprocess.Popen("git pull", cwd=os.path.expanduser(line.rstrip()), shell=True, stdout = subprocess.PIPE, stderr=subprocess.PIPE)
	(out, error)=pr.communicate()

f.close()

print str(out)
