#!/usr/bin/python

import os
import subprocess

# @TODO: Check if repos.txt exists. If not create one and edit it.
f = open(os.path.expanduser('~/.local/repos.txt'), 'r+')

for line in f:
	print line
	pr=subprocess.Popen("git pull", cwd=os.path.expanduser(line.rstrip()), shell=True, stdout = subprocess.PIPE, stderr=subprocess.PIPE)
	(out, error)=pr.communicate()
# @TODO: Best format.
	print str(out)


